# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag/v1/rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag/v1/rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rag/v1/rag.proto\x12\x06rag.v1\"h\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12*\n\nthink_mode\x18\x03 \x01(\x0e\x32\x11.rag.v1.ThinkModeH\x00\x88\x01\x01\x42\r\n\x0b_think_mode\"/\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08thinking\x18\x02 \x01(\t\"8\n\x15RetrieveChunksRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"7\n\x16RetrieveChunksResponse\x12\x1d\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\r.rag.v1.Chunk\"I\n\x05\x43hunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x13\n\x0b\x63hunk_index\x18\x04 \x01(\x05\"\x18\n\x16GetServerConfigRequest\"H\n\x17GetServerConfigResponse\x12-\n\x12\x64\x65\x66\x61ult_think_mode\x18\x01 \x01(\x0e\x32\x11.rag.v1.ThinkMode*W\n\tThinkMode\x12\x1a\n\x16THINK_MODE_UNSPECIFIED\x10\x00\x12\x17\n\x13THINK_MODE_DISABLED\x10\x01\x12\x15\n\x11THINK_MODE_HIDDEN\x10\x02\x32\xe3\x01\n\nRAGService\x12\x30\n\x03\x41sk\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse0\x01\x12O\n\x0eRetrieveChunks\x12\x1d.rag.v1.RetrieveChunksRequest\x1a\x1e.rag.v1.RetrieveChunksResponse\x12R\n\x0fGetServerConfig\x12\x1e.rag.v1.GetServerConfigRequest\x1a\x1f.rag.v1.GetServerConfigResponseB;Z9github.com/DanielBlei/go-to-rag/internal/gen/rag/v1;ragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag.v1.rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/DanielBlei/go-to-rag/internal/gen/rag/v1;ragv1'
  _globals['_THINKMODE']._serialized_start=473
  _globals['_THINKMODE']._serialized_end=560
  _globals['_ASKREQUEST']._serialized_start=28
  _globals['_ASKREQUEST']._serialized_end=132
  _globals['_ASKRESPONSE']._serialized_start=134
  _globals['_ASKRESPONSE']._serialized_end=181
  _globals['_RETRIEVECHUNKSREQUEST']._serialized_start=183
  _globals['_RETRIEVECHUNKSREQUEST']._serialized_end=239
  _globals['_RETRIEVECHUNKSRESPONSE']._serialized_start=241
  _globals['_RETRIEVECHUNKSRESPONSE']._serialized_end=296
  _globals['_CHUNK']._serialized_start=298
  _globals['_CHUNK']._serialized_end=371
  _globals['_GETSERVERCONFIGREQUEST']._serialized_start=373
  _globals['_GETSERVERCONFIGREQUEST']._serialized_end=397
  _globals['_GETSERVERCONFIGRESPONSE']._serialized_start=399
  _globals['_GETSERVERCONFIGRESPONSE']._serialized_end=471
  _globals['_RAGSERVICE']._serialized_start=563
  _globals['_RAGSERVICE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
