# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_forge._gen.rag.v1 import rag_pb2 as rag_dot_v1_dot_rag__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag/v1/rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RAGServiceStub(object):
    """RAGService exposes the retrieval-augmented generation pipeline over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_stream(
                '/rag.v1.RAGService/Ask',
                request_serializer=rag_dot_v1_dot_rag__pb2.AskRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.AskResponse.FromString,
                _registered_method=True)
        self.RetrieveChunks = channel.unary_unary(
                '/rag.v1.RAGService/RetrieveChunks',
                request_serializer=rag_dot_v1_dot_rag__pb2.RetrieveChunksRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.RetrieveChunksResponse.FromString,
                _registered_method=True)
        self.GetServerConfig = channel.unary_unary(
                '/rag.v1.RAGService/GetServerConfig',
                request_serializer=rag_dot_v1_dot_rag__pb2.GetServerConfigRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.GetServerConfigResponse.FromString,
                _registered_method=True)


class RAGServiceServicer(object):
    """RAGService exposes the retrieval-augmented generation pipeline over gRPC.
    """

    def Ask(self, request, context):
        """Ask queries the knowledge base and streams an LLM-generated answer
        grounded in the retrieved context. Each response message carries a token
        chunk so callers can display output incrementally or collect all chunks
        and act on the full answer once the stream closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunks(self, request, context):
        """RetrieveChunks returns scored chunks from the vector store without
        LLM generation. Designed for service-to-service use where the caller
        handles generation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerConfig(self, request, context):
        """GetServerConfig returns the server's current defaults so callers can
        understand what they get when optional fields are omitted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_stream_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.AskRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.AskResponse.SerializeToString,
            ),
            'RetrieveChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveChunks,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.RetrieveChunksRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.RetrieveChunksResponse.SerializeToString,
            ),
            'GetServerConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerConfig,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.GetServerConfigRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.GetServerConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.RAGService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.RAGService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """RAGService exposes the retrieval-augmented generation pipeline over gRPC.
    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RAGService/Ask',
            rag_dot_v1_dot_rag__pb2.AskRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RAGService/RetrieveChunks',
            rag_dot_v1_dot_rag__pb2.RetrieveChunksRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.RetrieveChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RAGService/GetServerConfig',
            rag_dot_v1_dot_rag__pb2.GetServerConfigRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.GetServerConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
